- task: Docker@2
  inputs:
    containerRegistry: 'azureACRpratham'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: CopyPublishBuildArtifacts@1
  inputs:
    Contents: 'deployment.azure.yaml'
    ArtifactName: 'deployment'
    ArtifactType: 'FilePath'